type QuoteProps = string;

export const QUOTES: QuoteProps[] = [
  'Life is a journey, not a destination.',
  'The only way to do great work is to love what you do.',
  'Success is not final, failure is not fatal: It is the courage to continue that counts.',
  'In the middle of every difficulty lies opportunity.',
  'Be yourself; everyone else is already taken.',
  'The best revenge is massive success.',
  'The only limit to our realization of tomorrow will be our doubts of today.',
  "Believe you can and you're halfway there.",
  'It does not matter how slowly you go as long as you do not stop.',
  "You miss 100% of the shots you don't take.",
  'The future belongs to those who believe in the beauty of their dreams.',
  'The harder I work, the luckier I get.',
  'The only person you should try to be better than is the person you were yesterday.',
  "Life is short, and it's up to you to make it sweet.",
  "Don't watch the clock; do what it does. Keep going.",
  'The journey of a thousand miles begins with one step.',
  'Do what you can, with what you have, where you are.',
  'The only way to predict the future is to create it.',
  'The greatest glory in living lies not in never falling, but in rising every time we fall.',
  "Your time is limited, don't waste it living someone else's life.",
  'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.',
  'Change your thoughts and you change your world.',
  'You are never too old to set another goal or to dream a new dream.',
  'The secret of getting ahead is getting started.',
  'Strive not to be a success, but rather to be of value.',
  'The only thing standing between you and your dream is the will to try and the belief that it is actually possible.',
  "Don't count the days, make the days count.",
  'The best way to predict the future is to create it.',
  'You are the only limit to your success.',
  'Dream big and dare to fail.',
  'The mind is everything. What you think, you become.',
  "It always seems impossible until it's done.",
  'Success is walking from failure to failure with no loss of enthusiasm.',
  'The power of imagination makes us infinite.',
  'Every moment is a fresh beginning.',
  'Life is 10% what happens to us and 90% how we react to it.',
  "Don't let yesterday take up too much of today.",
  'The only way to do great things is to love what you do.',
  'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.',
  'The purpose of our lives is to be happy.',
  'Challenges are what make life interesting, and overcoming them is what makes life meaningful.',
  "You don't have to be perfect to be amazing.",
  'The future starts today, not tomorrow.',
  "Don't stop until you're proud.",
  'Happiness is not something readymade. It comes from your own actions.',
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  'Life is really simple, but we insist on making it complicated.',
  'You are what you believe yourself to be.',
  'The only limit to our realization of tomorrow will be our doubts of today.',
  'Great things never come from comfort zones.',
];
